<?php
/*+**********************************************************************************
 * The contents of this file are subject to the NCRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  NCRM Open Source
 * The Initial Developer of the Original Code is ncrm.
 * Portions created by ncrm are Copyright (C) ncrm.
 * All Rights Reserved.
 ************************************************************************************/
require_once 'include/events/SqlResultIterator.inc';
require_once 'VTWorkflowManager.inc';
require_once 'VTTaskManager.inc';
require_once 'VTWorkflowTemplateManager.inc';
require_once 'VTTaskQueue.inc';
?>